import firebase from 'firebase';

var firebaseConfig = {
    apiKey: "AIzaSyCLEo3wpiSt3ka2L_qkeoCtz0UDP_Er97s",
    authDomain: "motivator-5c74b.firebaseapp.com",
    databaseURL: "https://motivator-5c74b-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "motivator-5c74b",
    storageBucket: "motivator-5c74b.appspot.com",
    messagingSenderId: "233151406584",
    appId: "1:233151406584:web:611d3d7bcc49c5b4e7b60d"
};

if (!firebase.apps.length)
    firebase.initializeApp(firebaseConfig);

var db = firebase.database();

function constructUserResult(user) {
    return {
        email: user.user.email,
        isSuccess: true
    }
}

function constructErrorResult(error) {
    return {
        error: error,
        isSuccess: false
    }
}

export const createUser = async function (email, password) {
    return new Promise((resolve) => {
        firebase.auth().createUserWithEmailAndPassword(email, password)
            .then((userCredential) => {
                resolve(constructUserResult(userCredential));
            })
            .catch((error) => {
                resolve(constructErrorResult(error));
            });
    })
        .then(r => r);
}

export const loginUser = function (email, password) {
    return new Promise((resolve) => {
        firebase.auth().signInWithEmailAndPassword(email, password)
            .then((userCredential) => {
                resolve(constructUserResult(userCredential));
            })
            .catch((error) => {
                resolve(constructErrorResult(error));
            });
    })
        .then(r => r);
}

export const createTask = function (name, details) {
    let userId = firebase.auth().currentUser.uid;
    db.ref('tasks').child(name).set({ ...details, userId: userId });
}

// let genericStructure = {
//     users: [
//         // id is generated by firebase's auth api and can be retrieved from firebase.auth().currentUser.uid;
//         id1: {
//            name: 'name' 
//         },
//         id2: {
//             name: 'name2'
//         }
//     ],
//     tasks: [
//         // Retrieve user-related objects by their key (for individual objects):
//             // db.ref('tasks').child('key1').once('value') 
//             // note that 'value' is a Firebase EventType, not anything specific to the data you are fetching.
//         // Or by their associated user (for a list of objects, e.g. on site load):
//             // db.ref('tasks').orderByChild('userId').equalTo('id1') 
//         key1: {
//             name: 'name1',
//             userId: id1,
//             description:'description'
//         },
//     ]
// }