import firebase from 'firebase';

var firebaseConfig = {
    apiKey: "AIzaSyCLEo3wpiSt3ka2L_qkeoCtz0UDP_Er97s",
    authDomain: "motivator-5c74b.firebaseapp.com",
    databaseURL: "https://motivator-5c74b-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "motivator-5c74b",
    storageBucket: "motivator-5c74b.appspot.com",
    messagingSenderId: "233151406584",
    appId: "1:233151406584:web:611d3d7bcc49c5b4e7b60d"
};

if (!firebase.apps.length)
    firebase.initializeApp(firebaseConfig);

var db = firebase.database();

export const logOut = function () {
    firebase.auth().signOut();
}

function constructUserResult(user) {
    return {
        id: user.user.uid,
        isSuccess: true
    }
}

function constructErrorResult(error) {
    return {
        error: error,
        isSuccess: false
    }
}

const addEqualToListener = function (tableName, columnName, queryValue, eventType, callback) {
    db.ref(tableName).orderByChild(columnName).equalTo(queryValue)
        .on(eventType, (snapshot) => {
            callback(tableName, snapshot);
        });
}

const getEqualTo = function (tableName, columnName, queryValue) {
    return new Promise(resolve => {
        db.ref(tableName).orderByChild(columnName).equalTo(queryValue)
            .on('value', (snapshot) => {
                resolve(snapshot);
            });
    })
        .then(r => r);
}

const getFromKey = function (tableName, keyValue) {
    return new Promise(resolve => {
        db.ref(tableName).child(keyValue).get()
            .then(snapshot => {
                resolve(snapshot);
            });
    })
        .then(r => r);
}

export const getCurrentUser = async function () {
    return await firebase.auth().currentUser;
}

export const createUser = async function (credentials, listenersCallback) {
    return createUserPromise(
        firebase.auth().createUserWithEmailAndPassword(credentials.email, credentials.password)
        , credentials, false, listenersCallback
    );
}

export const signInUser = async function (credentials, listenersCallback) {
    return createUserPromise(
        firebase.auth().signInWithEmailAndPassword(credentials.email, credentials.password)
        , credentials, true, listenersCallback
    );
}

const createUserPromise = async function (func, credentials, isSignIn, listenersCallback) {
    return new Promise((resolve) =>
        func
            .then((userCredential) => {
                resolve(constructUserResult(userCredential));
            })
            .catch((error) => {
                resolve(constructErrorResult(error));
            })
    )
        .then(async r => {
            if (!r.isSuccess)
                return r;

            addListeners(r.id, listenersCallback);

            if (!isSignIn) {
                db.ref('userDetails').push({ userId: r.id, ...credentials });
            }

            var details = credentials;
            if (isSignIn) {
                details = await getUserDetails(r.id);
                // Firebase returns the user's details like this:
                // { -tHEuSeR'SkeY: { ...theirDetails } }
                // So we have to access the nested object within the returned object.
                details = details[Object.keys(details)[0]];
                var data = await getUserData(r.id);
            }

            return { ...r, ...details, data: data }
        });
}

export const addListeners = function (userId, callback) {
    addEqualToListener('tasks', 'userId', userId, 'child_added', callback);
    addEqualToListener('tasks', 'userId', userId, 'child_changed', callback);
    addEqualToListener('prizes', 'userId', userId, 'child_added', callback);
    addEqualToListener('prizes', 'userId', userId, 'child_changed', callback);
}

export const getUserDetails = async function (userId) {
    let userDetails = await getEqualTo('userDetails', 'userId', userId);
    return userDetails.val();
}

export const getUserData = async function (userId) {
    let userTasks = await getEqualTo('tasks', 'userId', userId);
    let userPrizes = await getEqualTo('prizes', 'userId', userId);
    return { tasks: userTasks.val(), prizes: userPrizes.val() }
}

export const createTask = function (details, userId) {
    db.ref('tasks').push({ userId: userId, ...details });
}

export const createPrize = function (details, userId) {
    db.ref('prizes').push({ userId: userId, ...details });
}

const separateId = function (object) {
    let { id, ...details } = object;
    return { id: id, details: details };
}

export const updateTask = function (taskData) {
    let task = separateId(taskData);
    db.ref(`tasks/${task.id}/`).set(task.details);
}

export const updatePrize = function (prizeData) {
    let prize = separateId(prizeData);
    db.ref(`prizes/${prize.id}/`).set(prize.details);
}

// let genericStructure = {
//     users: [
//         // id is generated by firebase's auth api and can be retrieved from firebase.auth().currentUser.uid;
//         id1: {
//            name: 'name' 
//         },
//         id2: {
//             name: 'name2'
//         }
//     ],
//     tasks: [
//         // Retrieve user-related objects by their key (for individual objects):
//             // db.ref('tasks').child('key1').once('value') 
//             // note that 'value' is a Firebase EventType, not anything specific to the data you are fetching.
//         // Or by their associated user (for a list of objects, e.g. on site load):
//             // db.ref('tasks').orderByChild('userId').equalTo('id1') 
//         key1: {
//             name: 'name1',
//             userId: id1,
//             description:'description'
//         },
//     ]
// }